### ISSUE TITLE
サークル情報登録用 API (バックエンド) の設定

### ISSUE THREAD

**Issue by KashEight** [lc-tut/club-portal#1]
(加筆予定)

# 現状

## 認証
- 認証用 API は (ほぼ) 完成している
  - 認証済か: `/api/auth/`
  - ログイン処理: `/api/auth/signin`
  - コールバック: `/api/auth/callback`
  - 破棄: `/api/auth/destory`

## 環境 | CI/CD | テストなど
- Docker によるビルド & コンテナ化はできている

## サイト本体の API
#9 で決める予定

# 実装予定
## 認証
- 認証自体はほぼなし
- セッションとかの処理は改善必要かもしれない

## 環境 | CI/CD | テストなど
- GitHub Actions でデプロイ？
  - どういう形でデプロイするかはもう少し先に決めます
- テストコードは書きたい

## サイト本体の API
- 今の課題
- ここはフロントエンドとどういう連携をするかが重要なので難しい
- 今のところ考えているのは `/api/v1/` 以下の形で実装すること
  - サイト改修で API を大きく変更する時は `/api/v2/` みたいな形にする (改修する可能性は低そうだけど)
  - 構造的に近いのは Discord API あたり

# Tasks
- [x] サイト本体の API を作成
- [ ] GitHub Actions による CI/CD の自動化
- [ ] サイトを置くサーバを整える
- [ ] テストコード書く
- [ ] docs を書く (つまりコメントを書く)

**Comment by KashEight** [comment]
サーバに docker, docker-compose ぶっこんで少し整理しました
